name: Run Automation Tests

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minute
  workflow_dispatch:         # Manual trigger support
jobs:
  test:
    runs-on: windows-latest   #ubuntu-latest

    env:
      RP_API_KEY: ${{ secrets.RP_API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with ReportPortal
        run: |
          .\.venv\Scripts\activate
          # pytest -s -v -m "regression" --html=Reports\\report.html --self-contained-html testCases/ --browser chrome
          pytest -m "regression" testCases/
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: Reports/report.html
